{% set name = "yarr" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.cern.ch/yarr/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 56dd0a42f5260470239f76b89aad016913e8267fbf3e10227abf1797618de18d
  patches:
    - patches/0001-yarr_873.patch
    - patches/0002-patch-strip-debug.patch
    - patches/0003-patch-dependency-resolution-for-osx.patch

build:
  skip: true  # [win]
  script:
    - CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY" cmake ${CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX=$PREFIX -S "${SRC_DIR}" -B build  # [osx]
    - CXXFLAGS="${CXXFLAGS}" cmake ${CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX=$PREFIX -S "${SRC_DIR}" -B build  # [linux]
    - cmake --build build --clean-first --parallel="${CPU_COUNT}"
    - cmake --install build
    - mkdir -p $PREFIX/share/yarr
    - rsync -ravz $SRC_DIR/configs $PREFIX/share/yarr
    - find $PREFIX/share/yarr/configs -name '*.json' -type f -print -exec sed -i "s@\"configs/@\"$PREFIX/share/yarr/configs/@g" {} +
    - cat $PREFIX/share/yarr/configs/controller/emuCfg_rd53a.json
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - rsync
    - sed
  run:
    - gnuplot

test:
  commands:
    - test -f $PREFIX/bin/scanConsole
    - test -f $PREFIX/share/yarr/configs/controller/emuCfg_rd53a.json
    - cat $PREFIX/share/yarr/configs/controller/emuCfg_rd53a.json
    - scanConsole -h
    - scanConsole -k
    - scanConsole -r $PREFIX/share/yarr/configs/controller/emuCfg_rd53a.json -c $PREFIX/share/yarr/configs/connectivity/example_rd53a_setup.json -s $PREFIX/share/yarr/configs/scans/rd53a/std_digitalscan.json -p  # [linux]

about:
  home: https://gitlab.cern.ch/YARR/YARR
  summary: 'Yet Another Rapid Readout'
  description: |
    YARR is a readout system based around the concept of moving intelligence
    from the FPGA firmware into the host computer software. The role of the FPGA is
    the one of a reconfigurable I/O interface and not anymore the one of a hardware
    accelerator. YARR supports multiple types of FPGA platforms and readout chips.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  doc_url: https://yarr.web.cern.ch/yarr/
  dev_url: https://gitlab.cern.ch/YARR/YARR

extra:
  recipe-maintainers:
    - kratsg
